import type { Metadata } from "next";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

import "@/app/globals.css";

import QueryClientProvider from "./QueryClientProvider";
import NextAuthProvider from "./NextAuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body suppressHydrationWarning={true}>
        <NextAuthProvider>
          <QueryClientProvider>
            <div className="mx-auto flex max-w-[402px] flex-col bg-[#000414] pt-[env(safe-area-inset-top)] pb-[env(safe-area-inset-bottom)]">
              {children}
            </div>
            <ReactQueryDevtools />
          </QueryClientProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
