import type { Metadata } from "next";

import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import "@/app/globals.css";

import Head from "./head";
import QueryClientProvider from "./QueryClientProvider";
import NextAuthProvider from "./NextAuthProvider";
import { LoadingProvider } from "./LoadingProvider";

import { MotionConfig } from "motion/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <Head />
      <body suppressHydrationWarning={true}>
        <NextAuthProvider>
          <QueryClientProvider>
            <LoadingProvider>
              <MotionConfig 
                transition={{ 
                  duration: 0.4, 
                  ease: "easeInOut" 
                }}
                reducedMotion="user"
              >
                <div className="mx-auto flex w-screen max-w-[402px] flex-col bg-[#000414] pt-[env(safe-area-inset-top)] pb-[env(safe-area-inset-bottom)]">
                  {children}
                </div>
                <ReactQueryDevtools />
              </MotionConfig>
            </LoadingProvider>
          </QueryClientProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
